/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ruchika
 */
public class AboutUsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form AboutUsJPanel
     */
    public AboutUsJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
     
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        String URLString  = "welcome.png";
        imageLabel = new JLabel();
        imageLabel.setBounds(10,50,1500,800);
        add(imageLabel);  
        imageLabel.setIcon(ResizeImage(URLString));   
          
    }
    
    public ImageIcon ResizeImage(String ImagePath)
    {
         System.out.println(ImagePath);
//          imagePathTextInput.setText(ImagePath);
          ImageIcon MyImage = new ImageIcon(ImagePath);
          
          Image img = MyImage.getImage();
          Image newImg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon image = new ImageIcon(newImg);
          System.out.println(image);
          return image;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 255));
        setBorder(new javax.swing.border.MatteBorder(null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 12, 333, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nWe see many people have money but they dont know how to manage there events so here we bring \n\"Choice event management\" where you can register for events and  we take care of all the things then.\n\n\ncontact number:- +1 (857) 376 8540\n\nEmail:- choicemanagement@gmail.com\n\nThank you"); // NOI18N
        jTextArea1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 850, 424));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setText("Event Management Organisation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 11, -1, 42));

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngtree-back-icon-png-image_4627630-removebg-preview.jpg"))); // NOI18N
        backbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 995, 716));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
